<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageVersion Include="Microsoft.Azure.Cosmos" Version="3.63.1"/>
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12"/>


        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.4"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.4"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.4"/>


        <PackageVersion Include="xunit.v3" Version="4.0.1"/>
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0"/>
    </ItemGroup>
</Project>
