<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="Microsoft.Azure.Cosmos"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Analyzers\CustomerManagementSystem.Analyzers\CustomerManagementSystem.Analyzers.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\..\Analyzers\CustomerManagementSystem.CodeFixProviders\CustomerManagementSystem.CodeFixProviders.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CustomerManagementSystem.Domain\CustomerManagementSystem.Domain.csproj"/>
    </ItemGroup>
</Project>
